### ISSUE TITLE
i18n Externalizations tracking

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#963]
### Files to externalize

- Excludes admin templates / mailers and API documentation
- Includes currently unused templates

### templates
<details>
<summary>listing</summary>

<details>
<summary><code>welcome</code></summary>

- [x] `_root_organization_type_list.html.haml`
- [x] `choose_registration.html.haml`
- [x] `goodbye.html.haml`
- [x] `index.html.haml`
- [x] `recovery_stories.html.haml`
- [x] `update_browser.html.haml`
- [x] `user_home.html.haml`

</details>

<details>
<summary><code>layouts</code></summary>

- [x] `_grid.html.erb`
- [x] `_messages.html.haml`
- [x] `_messages_u.html.haml`
- [x] `_revised_messages.html.haml`
- [x] `application.html.haml`
- [x] `application_revised.html.haml`
- [x] `application_revised_bikehub.html.haml`
- [x] `email.html.haml`
- [x] `embed_layout.html.haml`
- [x] `embed_user_layout.html.haml`
- [x] `payments_layout.html.haml`
- [x] `reg_embed.html.haml`

</details>

<details>
<summary><code>shared</code></summary>

- [x] `_alert.html.haml`
- [x] `_charge.html.erb`
- [x] `_content_footer_ad.html.haml`
- [x] `_content_skeleton.html.haml`
- [x] `_donate_modal.html.haml`
- [x] `_edit_bike_skeleton.html.haml`
- [x] `_email_bike_box.html.haml`
- [x] `_faq.html.haml`
- [x] `_footer.html.haml`
- [x] `_footer_revised.html.haml`
- [x] `_footer_updated.html.haml`
- [x] `_form_well_footer_save.html.haml`
- [x] `_header.html.haml`
- [x] `_header_nav.html.haml`
- [x] `_modal.html.haml`
- [x] `_organized_skeleton.html.haml`
- [x] `_period_select.html.haml`
- [x] `_share_this.html.erb`
- [x] `_shops_map.html.erb`
- [x] `_top_user_nav.html.haml`
- [x] `_trash_icon.html.haml`

</details>

<details>
<summary><code>sessions</code></summary>

- [x] `new.html.haml`

</details>

<details>
<summary><code>landing_pages</code></summary>

- [x] `_for_organizations_photo_list.html.haml`
- [x] `_next_steps_contact.html.haml`
- [x] `_packages_list.html.haml`
- [x] `_tweet.html.haml`
- [x] `bike_shop_packages.html.haml`
- [x] `campus_packages.html.haml`
- [x] `cities_packages.html.haml`

</details>

<details>
<summary><code>kaminari</code></summary>

- [x] `_first_page.html.haml`
- [x] `_gap.html.haml`
- [x] `_last_page.html.haml`
- [x] `_next_page.html.haml`
- [x] `_page.html.haml`
- [x] `_paginator.html.haml`
- [x] `_prev_page.html.haml`

</details>

<details>
<summary><code>users</code></summary>

- [x] `_edit_password.html.haml`
- [x] `_edit_root.html.haml`
- [x] `_edit_sharing.html.haml`
- [x] `accept_terms.html.haml`
- [x] `accept_vendor_terms.html.haml`
- [x] `confirm_error_404.html.haml`
- [x] `confirm_error_bad_token.html.haml`
- [x] `edit.html.haml`
- [x] `globalid.html.haml`
- [x] `new.html.haml`
- [x] `organization_show.html.haml`
- [x] `password_reset.html.haml`
- [x] `please_confirm_email.html.haml`
- [x] `request_password_reset.html.haml`
- [x] `show.html.haml`
- [x] `update_password.html.haml`

</details>

<details>
<summary><code>organized</code></summary>

- [x] `ambassador_dashboards/getting_started.html.haml`
- [x] `ambassador_dashboards/resources.html.haml`
- [x] `ambassador_dashboards/show.html.haml`
- [x] `bikes/_list.html.haml`
- [x] `bikes/_search.html.haml`
- [x] `bikes/incompletes.html.haml`
- [x] `bikes/index.html.haml`
- [x] `bikes/multi_serial_search.html.haml`
- [x] `bikes/new.html.haml`
- [x] `bikes/recoveries.html.haml`
- [x] `bulk_imports/index.html.haml`
- [x] `bulk_imports/new.html.haml`
- [x] `bulk_imports/show.html.haml`
- [x] `exports/index.html.haml`
- [x] `exports/new.html.haml`
- [x] `exports/show.html.haml`
- [x] `manage/_location_fields.html.haml`
- [x] `manage/index.html.haml`
- [x] `manage/locations.html.haml`
- [x] `messages/index.html.haml`
- [x] `messages/show.html.haml`
- [x] `stickers/edit.html.haml`
- [x] `stickers/index.html.haml`
- [x] `users/edit.html.haml`
- [x] `users/index.html.haml`
- [x] `users/new.html.haml`
</details>

<details>
<summary><code>bikes</code></summary>

- [x] `app/views/bikes/_bike.html.haml`
- [x] `app/views/bikes/_bike_org_table.html.haml`
- [x] `app/views/bikes/_bike_show_overlays.html.haml`
- [x] `app/views/bikes/_bike_table.html.haml`
- [x] `app/views/bikes/_bike_u.html.haml`
- [x] `app/views/bikes/_edit_primary_menu.html.haml`
- [x] `app/views/bikes/_organized_access_panel.html.haml`
- [x] `app/views/bikes/_stolen_checklist.html.haml`
- [x] `app/views/bikes/_stolen_map.html.erb`
- [x] `app/views/bikes/_theft_alerts_table.html.haml`
- [x] `app/views/bikes/bike_fields/_revised_colors.html.haml`
- [x] `app/views/bikes/bike_fields/_revised_component_fields.html.haml`
- [x] `app/views/bikes/bike_fields/_stolen_location.html.haml`
- [x] `app/views/bikes/edit_accessories.html.haml`
- [x] `app/views/bikes/edit_alert.html.haml`
- [x] `app/views/bikes/edit_alert_purchase.html.haml`
- [x] `app/views/bikes/edit_alert_purchase_confirmation.html.haml`
- [x] `app/views/bikes/edit_bike_details.html.haml`
- [x] `app/views/bikes/edit_drivetrain.html.haml`
- [x] `app/views/bikes/edit_groups.html.haml`
- [x] `app/views/bikes/edit_ownership.html.haml`
- [x] `app/views/bikes/edit_photos.html.haml`
- [x] `app/views/bikes/edit_publicize.html.haml`
- [x] `app/views/bikes/edit_remove.html.haml`
- [x] `app/views/bikes/edit_report_recovered.html.haml`
- [x] `app/views/bikes/edit_report_stolen.html.haml`
- [x] `app/views/bikes/edit_theft_details.html.haml`
- [x] `app/views/bikes/index.html.haml`
- [x] `app/views/bikes/new.html.haml`
- [x] `app/views/bikes/pdf.html.haml`
- [x] `app/views/bikes/scanned.html.haml`
- [x] `app/views/bikes/show.html.haml`
- [x] `app/views/bikes/spokecard.html.haml`

</details>

<details>
<summary><code>errors</code></summary>

- [x] `bad_request.html.erb`
- [x] `not_found.html.erb`
- [x] `unauthorized.html.erb`
- [x] `unprocessable_entity.html.erb`

</details>

<details>
<summary><code>info</code></summary>

- [x] `_terms_text.html.erb`
- [x] `_vendor_terms_text.html.erb`
- [x] `privacy.html.erb`
- [x] `about.html.haml`
- [x] `dev_and_design.html.haml`
- [x] `image_resources.html.haml`
- [x] `lightspeed.html.haml`
- [x] `protect_your_bike.html.haml`
- [x] `resources.html.haml`
- [x] `serials.html.haml`
- [x] `support_bike_index.html.haml`
- [x] `terms.html.haml`
- [x] `vendor_terms.html.haml`
- [x] `where.html.haml`

</details>

<details>
<summary><code>organized_mailer</code></summary>

- [x] `finished_registration.html.haml`
- [x] `geolocated_message.html.haml`
- [x] `organization_invitation.html.haml`
- [x] `partial_registration.html.haml`

</details>

<details>
<summary><code>customer_mailer</code></summary>

- [x] `additional_email_confirmation.html.haml`
- [x] `confirmation_email.html.haml`
- [x] `invoice_email.html.haml`
- [x] `invoice_notification_email.html.haml`
- [x] `password_reset_email.html.haml`
- [x] `recovered_from_link.html.haml`
- [x] `stolen_bike_alert_email.html.erb`
- [x] `stolen_notification_email.html.haml`
- [x] `updated_terms_email.html.haml`
- [x] `welcome_email.html.haml`
</details>

<details>
<summary><code>locks</code></summary>

- [x] `_form.html.haml`
- [x] `_lock_home.html.haml`
- [x] `edit.html.haml`
- [x] `new.html.haml`
</details>

<details>
<summary><code>organization_invitations</code></summary>

- [x] `new.html.haml`
- [x] `not_available.html.haml`

</details>

<details>
<summary><code>payments</code></summary>

- [x] `_form.html.haml`
- [x] `create.html.haml`
- [x] `new.html.haml`

</details>

<details>
<summary><code>registrations</code></summary>

- [x] `create.html.haml`
- [x] `embed.html.haml`
- [x] `new.html.haml`

</details>

<details>
<summary><code>organizations</code></summary>

- [x] `_new_form.html.haml`
- [x] `embed.html.haml`
- [x] `embed_create_success.html.haml`
- [x] `embed_extended.html.haml`
- [x] `new.html.haml`

</details>

<details>
<summary><code>public_images</code></summary>

- [x] `_new_form.html.erb`
- [x] `_public_image.html.erb`
- [x] `show.html.erb`
- [x] `edit.html.erb`
- [x] `new.html.erb`
- [x] `_form.html.haml`
- [x] `_revised_public_image.html.haml`
- [x] `create.html.haml`

</details>

<details>
<summary><code>misc</code></summary>

- [x] `feedbacks/_form.html.haml`
- [x] `feedbacks/index.html.haml`
- [x] `manufacturers/index.html.haml`
- [x] `memberships/edit.html.haml`
- [x] `news/index.html.haml`
- [x] `news/show.html.haml`
- [x] `recovery_displays/_recovery_display.html.haml`
- [x] `stolen/_stickers.html.haml`
- [x] `stolen/index.html.haml`
- [x] `stolen_notifications/_form.html.haml`
- [x] `theft_alert_plans/_theft_alert_plan.html.haml`
- [x] `user_embeds/show.html.haml`

</details>

- [x] `shared/_errors.html.haml`
</details>

### models

<details>
<summary>listing</summary>

- [x] payment.rb
- [x] manufacturer.rb
- [x] bike_code.rb
- [x] impound_record.rb
- [x] integration.rb
- [x] bike.rb
- [x] theft_alert.rb
- [x] export.rb
- [x] organization_message.rb
- [x] recovery_display.rb
- [x] user.rb

</details>

### decorators & helpers

<details>
<summary>listing</summary>

- [x] bike_decorator.rb
- [x] lock_decorator.rb
- [x] paginating_decorator.rb
- [x] header_tag_helper.rb

</details>

### controllers

<details>
<summary>listing</summary>

- [x] application_controller.rb
- [x] theft_alerts_controller.rb
- [x] organizations_controller.rb
- [x] public_images_controller.rb
- [x] stolen_notifications_controller.rb
- [x] payments_controller.rb
- [x] sessions_controller.rb
- [x] welcome_controller.rb
- [x] feedbacks_controller.rb
- [x] integrations_controller.rb
- [x] locks_controller.rb
- [x] bikes_controller.rb
- [x] bike_codes_controller.rb
- [x] bikes/recovery_controller.rb
- [x] ownerships_controller.rb
- [x] user_emails_controller.rb
- [x] users_controller.rb
- [x] oauth/applications_controller.rb
- [x] organized/messages_controller.rb
- [x] organized/base_controller.rb
- [x] organized/exports_controller.rb
- [x] organized/manage_controller.rb
- [x] organized/users_controller.rb
- [x] organized/stickers_controller.rb
- [x] organized/bulk_imports_controller.rb
- [x] organized/ambassador_task_assignments_controller.rb
- [x] organized/bikes_controller.rb
- [x] concerns/sessionable.rb
- [x] concerns/controller_helpers.rb

</details>

### misc
- [x] Stripe donations checkout
- [x] Stripe promoted alerts checkout
- [x] React components (some assembly required. see: [react-rails-i18n](https://shakacode.gitbooks.io/react-on-rails/content/docs/basics/i18n.html) and [i18n-js](https://github.com/fnando/i18n-js))

**Comment by jmromer** [comment]
The following partials are not referenced directly by any code:

#### `app/javascript/stylesheets/`

- [ ] `_admin.scss`
- [ ] `_alerts.scss`
- [ ] `_table_extensions.scss`
- [ ] `_tweets.scss`
- [ ] `_utils.scss`

#### `app/views/`

- [ ] `admin/kaminari/_first_page.html.haml`
- [ ] `admin/kaminari/_last_page.html.haml`
- [ ] `admin/kaminari/_next_page.html.haml`
- [ ] `admin/kaminari/_page.html.haml`
- [ ] `admin/kaminari/_paginator.html.haml`
- [ ] `admin/kaminari/_prev_page.html.haml`
- [ ] `admin/organizations/custom_layouts/_landing_page.html.haml`
- [ ] `admin/organizations/custom_layouts/_mail_snippet.html.haml`
- [ ] `bikes/_bike_org_table.html.haml`
- [ ] `bikes/_bike_table.html.haml`
- [ ] `bikes/_bike_u.html.haml`
- [ ] `documentation/_authentication_info.haml`
- [ ] `documentation/_extend_authentication_info.markdown`
- [ ] `documentation/api_v2/_info_footer.markdown`
- [ ] `documentation/api_v2/_info_header.markdown`
- [ ] `documentation/api_v3/_info_header.markdown`
- [ ] `kaminari/_first_page.html.haml`
- [ ] `kaminari/_gap.html.haml`
- [ ] `kaminari/_last_page.html.haml`
- [ ] `kaminari/_next_page.html.haml`
- [ ] `kaminari/_page.html.haml`
- [ ] `kaminari/_paginator.html.haml`
- [ ] `kaminari/_prev_page.html.haml`
- [ ] `landing_pages/_footer.haml`
- [ ] `landing_pages/_header_ascend_svg.html.erb`
- [ ] `landing_pages/_next_steps_contact.html.haml`
- [ ] `landing_pages/icons/_footer_bike_shops_svg.html.erb`
- [ ] `landing_pages/icons/_header_ascend_svg.html.erb`
- [ ] `landing_pages/icons/_header_bike_shops_svg.html.erb`
- [ ] `landing_pages/icons/_header_cities_svg.html.erb`
- [ ] `landing_pages/icons/_header_community_groups_svg.html.erb`
- [ ] `landing_pages/icons/_header_law_enforcement_svg.html.erb`
- [ ] `landing_pages/icons/_header_school_svg.html.erb`
- [ ] `layouts/_grid.html.erb`
- [ ] `layouts/_messages_u.html.haml`
- [ ] `locks/_lock_home.html.haml`
- [ ] `public_images/_new_form.html.erb`
- [ ] `recovery_displays/_recovery_display.html.haml`
- [ ] `shared/_charge.html.erb`
- [ ] `shared/_content_skeleton.html.haml`
- [ ] `shared/_edit_bike_skeleton.html.haml`
- [ ] `shared/_facebook_pixel.html`
- [ ] `shared/_organized_skeleton.html.haml`
- [ ] `shared/_top_user_nav.html.haml`
- [ ] `stolen/_stickers.html.haml`
- [ ] `stolen_notifications/_form.html.haml`
- [ ] `theft_alert_plans/_theft_alert_plan.html.haml`
- [ ] `users/_edit_password.html.haml`
- [ ] `users/_edit_root.html.haml`
- [ ] `users/_edit_sharing.html.haml`

The following partials are only referenced directly by the partials above:

- [ ] `landing_pages/icons/_footer_community_groups_svg.html.erb`
- [ ] `landing_pages/icons/_footer_law_enforcement_svg.html.erb`
- [ ] `landing_pages/icons/_footer_school_svg.html.erb`
- [ ] `landing_pages/icons/_footer_shop_svg`


Some of the partials above (at any level) might be referenced dynamically by the following lines of code:

- [ ] `app/controllers/bikes_controller.rb`: `render "edit_#{@edit_template}".to_sym`
- [ ] `app/models/mail_snippet.rb`: `partial: "Below \"Finish it\" button, in email \"Partial registration\"",`
- [ ] `app/views/landing_pages/ascend.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/landing_pages/for_bike_shops.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/landing_pages/for_cities.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/landing_pages/for_community_groups.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/landing_pages/for_law_enforcement.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/landing_pages/for_schools.haml`: `= render "/landing_pages/icons/header_#{landing_page_target}_svg"`
- [ ] `app/views/layouts/application_revised.html.haml`: `= render "/shared/#{current_page_skeleton}"`
- [ ] `app/views/users/edit.html.haml`: `= render partial: "edit_#{@edit_template}", locals: { f: f }`

**Comment by sethherr** [comment]
Quick first look

- all the `scss` files you referenced are imported in https://github.com/bikeindex/bike_index/blob/master/app/javascript/packs/application_css.scss
- the `users/_edit_*` pages are rendered by app/views/users/edit.html.haml
- kaminari references things inside the gem, I'm not all are necessary but I'm not sure it's worth devoting much time to, those files were all generate automatically by kaminari.

**Comment by sethherr** [comment]
Just pinging on this - are the checks here accurate? Or is this all done?

**Comment by jmromer** [comment]
Thanks for the bump — I added file listings for the remaining categories. Still WIP.
